<?php


namespace app\admin\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class AdminBase extends BaseController
{
    public $adminUser = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
//        if (empty($this->isLogin())){
//           // return $this->redirect(url('login/index'));
//        }
    }

    //检测用户是否登录
    public function isLogin(){

        $this->adminUser   =   session(config('session.admin_session'));
        if (empty($this->adminUser)){

            return false;
        }
        return true;
    }

    //重写redirect方法
    public function redirect(...$args){

        throw new HttpResponseException(redirect(...$args));
    }
}