<?php
/**
 * Created by PengJu
 * User: RenPengJu
 * Motto: 现在的努力是为了小时候吹过的牛逼
 * Time: 2021/1/10/20:19
 */
namespace app\api\controller;

use app\BaseController;

use think\exception\HttpResponseException;

class ApiBase extends BaseController{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args){

        throw new HttpResponseException(show(...$args));

    }

}