<?php
/**
 * Created by PengJu
 * User: RenPengJu
 * Motto: 现在的努力是为了小时候吹过的牛逼
 * Time: 2021/1/10/20:21
 */
namespace app\api\controller;
use think\facade\Cache;

class AuthBase extends ApiBase{
    public $accessToken = "";

    public $username = '';

    public $id = 0;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->accessToken = $this->request->header("Access-Token");
        if (!$this->accessToken || !$this->isLogin()){
            return $this->show(config('status.not_login'),'你还没有登录');
        }
    }

    /**
     * 检测用户是否登录
     * @return bool
     * @date 2021/1/11/20:54
     * @author RenPengJu
     */
    public function isLogin(){

        $userInfo = Cache::get(config('redis.token_pre').$this->accessToken);
        if (!$userInfo){
            return false;
          }

        if (!empty($userInfo['id']) && !empty($userInfo['username'])){

            $this->id = $userInfo['id'];

            $this->username = $userInfo['username'];
            return true;
        }


        return  false;
    }
}